# Tenssor Basics

In [3]:
# Tensor Basics
import torch
import numpy as np

In [2]:
torch.__version__

'1.9.1+cpu'

In [5]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(type(arr))

int32
<class 'numpy.ndarray'>


In [7]:
x = torch.from_numpy(arr)

In [8]:
print(type(x))

<class 'torch.Tensor'>


In [9]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [10]:
x.dtype

torch.int32

In [12]:
arr2d = np.arange(0.0,12.0)
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [13]:
x2 = torch.from_numpy(arr2d)

In [14]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)